import type { ElementCategory } from './types'

export const ELEMENT_CATEGORIES: ElementCategory[] = [
  {
    id: 'surfaces', label: 'Surfaces', icon: 'road', color: '#374151',
    elements: [
      { id: 'surface-asphalt', label: 'Asphalt', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#1F2937', fillOpacity: 95, strokeWidth: 0 }, defaultProps: {} },
      { id: 'surface-concrete', label: 'Concrete', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB', fillOpacity: 90, strokeWidth: 0 }, defaultProps: {} },
      { id: 'surface-pavers', label: 'Unit Pavers', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#A8A29E', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-pavers-brick', label: 'Brick Pavers', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#92400E', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-pavers-cobble', label: 'Cobblestone', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#78716C', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-concrete-stamped', label: 'Stamped Concrete', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB', fillOpacity: 90 }, defaultProps: {} },
      { id: 'surface-permeable-asphalt', label: 'Permeable Asphalt', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#374151', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-permeable-concrete', label: 'Permeable Concrete', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#CBD5E1', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-gravel', label: 'Gravel / Crushed Stone', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#D97706', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-decomposed-granite-road', label: 'Decomposed Granite (Road)', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#C2842A', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-dirt', label: 'Unpaved / Dirt', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#92400E', fillOpacity: 80 }, defaultProps: {} },
      { id: 'surface-rubber', label: 'Rubber Surface', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#1C1917', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-turf-grid', label: 'Turf Grid / Grass Paving', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#A3E635', fillOpacity: 100 }, defaultProps: {} },
      { id: 'surface-paint-green', label: 'Green Paint (NACTO)', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#16A34A', fillOpacity: 75 }, defaultProps: {} },
      { id: 'surface-paint-red', label: 'Red Paint', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#DC2626', fillOpacity: 75 }, defaultProps: {} },
      { id: 'surface-paint-blue', label: 'Blue Paint', category: 'surfaces', drawMode: 'polygon', defaultStyle: { fillColor: '#2563EB', fillOpacity: 75 }, defaultProps: {} },
    ]
  },
  {
    id: 'streets', label: 'Street Sections', icon: 'road', color: '#374151',
    elements: [
      { id: 'local-street', label: 'Local Street', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#1F2937', strokeWidth: 2 }, defaultProps: { rowWidth: 45 } },
      { id: 'collector-street', label: 'Collector Street', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#1F2937', strokeWidth: 3 }, defaultProps: { rowWidth: 60 } },
      { id: 'arterial', label: 'Arterial / Boulevard', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#1F2937', strokeWidth: 4 }, defaultProps: { rowWidth: 90 } },
      { id: 'highway', label: 'Highway / Freeway', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#111827', strokeWidth: 6 }, defaultProps: { rowWidth: 200 } },
      { id: 'ped-street', label: 'Pedestrian Street / Woonerf', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#A8A29E', strokeWidth: 2 }, defaultProps: { rowWidth: 30 } },
      { id: 'alley', label: 'Alley / Service Lane', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#374151', strokeWidth: 1 }, defaultProps: { rowWidth: 16 } },
      { id: 'bike-lane', label: 'Protected Bike Lane / Cycle Track', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#16A34A', strokeWidth: 2 }, defaultProps: { rowWidth: 8 } },
      { id: 'shared-path', label: 'Shared Use Path / Greenway', category: 'streets', drawMode: 'line', defaultStyle: { strokeColor: '#D1D5DB', strokeWidth: 2 }, defaultProps: { rowWidth: 12 } },
    ]
  },
  {
    id: 'markings', label: 'Markings & Signage', icon: 'map', color: '#FBBF24',
    elements: [
      { id: 'dbl-yellow', label: 'Double Solid Yellow Centerline', category: 'markings', drawMode: 'line', defaultStyle: { strokeColor: '#FBBF24', strokeWidth: 1 }, defaultProps: {} },
      { id: 'solid-yellow', label: 'Single Solid Yellow Line', category: 'markings', drawMode: 'line', defaultStyle: { strokeColor: '#FBBF24', strokeWidth: 1 }, defaultProps: {} },
      { id: 'broken-white', label: 'Broken White Lane Line', category: 'markings', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', lineType: 'dashed', strokeWidth: 1 }, defaultProps: {} },
      { id: 'solid-white', label: 'Solid White Lane Line', category: 'markings', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: {} },
      { id: 'stop-bar', label: 'Stop Bar', category: 'markings', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 3 }, defaultProps: {} },
      { id: 'hatch-box', label: 'Diagonal Hatch Box', category: 'markings', drawMode: 'polygon', defaultStyle: { fillColor: '#FFFFFF', fillOpacity: 40 }, defaultProps: {} },
      { id: 'colored-pvmt', label: 'Colored Pavement Area', category: 'markings', drawMode: 'polygon', defaultStyle: { fillColor: '#16A34A', fillOpacity: 75 }, defaultProps: {} },
      { id: 'direction-arrow', label: 'Direction Arrow', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: {} },
      { id: 'left-turn-arrow', label: 'Left Turn Arrow', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: {} },
      { id: 'right-turn-arrow', label: 'Right Turn Arrow', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: {} },
      { id: 'only-stencil', label: 'ONLY Stencil', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: {} },
      { id: 'sharrow', label: 'Bicycle Stencil / Sharrow', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#16A34A' }, defaultProps: {} },
      { id: 'bus-only-stencil', label: 'BUS ONLY Stencil', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#DC2626' }, defaultProps: {} },
      { id: 'stop-sign', label: 'Stop Sign (R1-1)', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#DC2626' }, defaultProps: {} },
      { id: 'yield-sign', label: 'Yield Sign (R1-2)', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#DC2626' }, defaultProps: {} },
      { id: 'speed-sign', label: 'Speed Limit Sign', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: { speed: 25 } },
      { id: 'no-parking-sign', label: 'No Parking Sign', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: {} },
      { id: 'street-name-sign', label: 'Street Name Sign', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#16A34A' }, defaultProps: {} },
      { id: 'wayfinding-sign', label: 'Wayfinding / Directional Sign', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#2563EB' }, defaultProps: {} },
      { id: 'parking-meter', label: 'Parking Meter / Pay Station', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#64748B' }, defaultProps: {} },
      { id: 'traffic-signal', label: 'Traffic Signal', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#111827' }, defaultProps: {} },
      { id: 'ped-signal', label: 'Pedestrian Signal', category: 'markings', drawMode: 'place', defaultStyle: { fillColor: '#111827' }, defaultProps: {} },
    ]
  },
  {
    id: 'crosswalks', label: 'Crosswalks', icon: 'measure', color: '#2563EB',
    elements: [
      { id: 'std-crosswalk', label: 'Standard Crosswalk (Type B)', category: 'crosswalks', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 2 }, defaultProps: {} },
      { id: 'continental-crosswalk', label: 'Continental Crosswalk', category: 'crosswalks', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 2 }, defaultProps: {} },
      { id: 'raised-crosswalk', label: 'Raised Crosswalk / Speed Table', category: 'crosswalks', drawMode: 'line', defaultStyle: { strokeColor: '#A8A29E', strokeWidth: 3 }, defaultProps: {} },
      { id: 'refuge-island', label: 'Pedestrian Refuge Island', category: 'crosswalks', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB' }, defaultProps: {} },
      { id: 'curb-extension', label: 'Curb Extension / Bulb-Out', category: 'crosswalks', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB' }, defaultProps: {} },
    ]
  },
  {
    id: 'parking', label: 'Parking', icon: 'rect', color: '#64748B',
    elements: [
      { id: 'parallel-parking', label: 'Parallel Parking', category: 'parking', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { stallWidth: 8, stallLength: 22 } },
      { id: 'headin-parking', label: 'Head-In (90°) Parking', category: 'parking', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { stallWidth: 9, stallLength: 18 } },
      { id: 'diagonal-parking', label: 'Diagonal Parking', category: 'parking', drawMode: 'line', defaultStyle: { strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { angle: 45, stallWidth: 9 } },
      { id: 'surface-lot', label: 'Surface Parking Lot', category: 'parking', drawMode: 'polygon', defaultStyle: { fillColor: '#1F2937', fillOpacity: 85 }, defaultProps: {} },
      { id: 'parking-deck-bldg', label: 'Parking Structure', category: 'parking', drawMode: 'polygon', defaultStyle: { fillColor: '#374151' }, defaultProps: { levels: 4 } },
    ]
  },
  {
    id: 'transit', label: 'Transit', icon: 'road', color: '#DC2626',
    elements: [
      { id: 'bus-route', label: 'Bus Route Line', category: 'transit', drawMode: 'line', defaultStyle: { strokeColor: '#DC2626', strokeWidth: 3 }, defaultProps: {} },
      { id: 'bus-only-lane', label: 'Bus-Only Lane', category: 'transit', drawMode: 'line', defaultStyle: { strokeColor: '#DC2626', strokeWidth: 2 }, defaultProps: {} },
      { id: 'bus-stop', label: 'Bus Stop', category: 'transit', drawMode: 'place', defaultStyle: { fillColor: '#2563EB' }, defaultProps: {} },
      { id: 'brt-station', label: 'BRT Station', category: 'transit', drawMode: 'place', defaultStyle: { fillColor: '#EA580C' }, defaultProps: {} },
      { id: 'rail-station', label: 'Rail / Metro Station', category: 'transit', drawMode: 'place', defaultStyle: { fillColor: '#7C3AED' }, defaultProps: {} },
      { id: 'rail-track', label: 'Rail Track', category: 'transit', drawMode: 'line', defaultStyle: { strokeColor: '#374151', strokeWidth: 2 }, defaultProps: {} },
      { id: 'ferry-terminal', label: 'Ferry Terminal', category: 'transit', drawMode: 'place', defaultStyle: { fillColor: '#2563EB' }, defaultProps: {} },
    ]
  },
  {
    id: 'paths', label: 'Paths', icon: 'bike', color: '#16A34A',
    elements: [
      { id: 'sidewalk', label: 'Sidewalk', category: 'paths', drawMode: 'line', defaultStyle: { strokeColor: '#D1D5DB', strokeWidth: 2 }, defaultProps: { width: 5 } },
      { id: 'multi-path', label: 'Multi-Use Path', category: 'paths', drawMode: 'line', defaultStyle: { strokeColor: '#D1D5DB', strokeWidth: 2 }, defaultProps: { width: 12 } },
      { id: 'steps', label: 'Steps / Stairs', category: 'paths', drawMode: 'line', defaultStyle: { strokeColor: '#D1D5DB', strokeWidth: 2 }, defaultProps: {} },
      { id: 'ada-ramp', label: 'ADA Accessible Ramp', category: 'paths', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB' }, defaultProps: {} },
      { id: 'footbridge', label: 'Footbridge / Pedestrian Bridge', category: 'paths', drawMode: 'line', defaultStyle: { strokeColor: '#9CA3AF', strokeWidth: 2 }, defaultProps: {} },
      { id: 'ped-tunnel', label: 'Tunnel / Underpass', category: 'paths', drawMode: 'line', defaultStyle: { strokeColor: '#374151', lineType: 'dashed', strokeWidth: 2 }, defaultProps: {} },
    ]
  },
  {
    id: 'furniture', label: 'Street Furniture', icon: 'tree', color: '#92400E',
    elements: [
      { id: 'bench', label: 'Bench', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#92400E' }, defaultProps: {} },
      { id: 'table-chairs', label: 'Table & Chairs', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#78716C' }, defaultProps: {} },
      { id: 'picnic-table', label: 'Picnic Table', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#78716C' }, defaultProps: {} },
      { id: 'seating-steps', label: 'Seating Steps', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB' }, defaultProps: {} },
      { id: 'street-light', label: 'Street Light', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#64748B' }, defaultProps: {}, nightModeEmitter: true, illuminationRadius: 40 },
      { id: 'ped-light', label: 'Pedestrian Light', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#78716C' }, defaultProps: {}, nightModeEmitter: true, illuminationRadius: 20 },
      { id: 'string-lights', label: 'String Lights', category: 'furniture', drawMode: 'line', defaultStyle: { strokeColor: '#FCD34D', strokeWidth: 1 }, defaultProps: { sag: 'medium', spacing: 2 }, nightModeEmitter: true, illuminationRadius: 4 },
      { id: 'accent-light', label: 'Accent Light', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#FCD34D' }, defaultProps: {}, nightModeEmitter: true, illuminationRadius: 5 },
      { id: 'bike-rack', label: 'Bicycle Rack', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#64748B' }, defaultProps: {} },
      { id: 'bike-corral', label: 'Bike Corral', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#64748B', fillOpacity: 30 }, defaultProps: {} },
      { id: 'bike-share', label: 'Bike Share Station', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#2563EB' }, defaultProps: {} },
      { id: 'bollard', label: 'Bollard', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#374151' }, defaultProps: {} },
      { id: 'jersey-barrier', label: 'Jersey Barrier', category: 'furniture', drawMode: 'line', defaultStyle: { strokeColor: '#9CA3AF', strokeWidth: 2 }, defaultProps: {} },
      { id: 'fence-railing', label: 'Fence / Railing', category: 'furniture', drawMode: 'line', defaultStyle: { strokeColor: '#78716C', strokeWidth: 1 }, defaultProps: { type: 'wood' } },
      { id: 'retaining-wall', label: 'Retaining Wall', category: 'furniture', drawMode: 'line', defaultStyle: { strokeColor: '#9CA3AF', strokeWidth: 2 }, defaultProps: { height: 4 } },
      { id: 'waste-bin', label: 'Waste Receptacle', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#374151' }, defaultProps: {} },
      { id: 'dog-waste-station', label: 'Dog Waste Station', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#16A34A' }, defaultProps: {} },
      { id: 'bollard-planter', label: 'Bollard Planter', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#78716C' }, defaultProps: {} },
      { id: 'planter-box', label: 'Planter Box', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#78716C' }, defaultProps: {} },
      { id: 'fountain', label: 'Fountain', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#3B82F6' }, defaultProps: {} },
      { id: 'pergola', label: 'Pergola', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#92400E', fillOpacity: 40 }, defaultProps: {} },
      { id: 'kiosk', label: 'Kiosk', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#374151' }, defaultProps: {} },
      { id: 'public-art', label: 'Public Art', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#7C3AED' }, defaultProps: {} },
      { id: 'monument', label: 'Monument', category: 'furniture', drawMode: 'place', defaultStyle: { fillColor: '#64748B' }, defaultProps: {} },
      { id: 'playground', label: 'Playground Area', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'dog-park', label: 'Dog Park', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#D9F99D', fillOpacity: 60 }, defaultProps: {} },
      { id: 'community-garden', label: 'Community Garden', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#84CC16', fillOpacity: 60 }, defaultProps: {} },
      { id: 'sports-court', label: 'Sports Court / Field', category: 'furniture', drawMode: 'polygon', defaultStyle: { fillColor: '#374151', fillOpacity: 80 }, defaultProps: { sport: 'basketball' } },
    ]
  },
  {
    id: 'utilities', label: 'Utilities', icon: 'settings', color: '#64748B',
    elements: [
      { id: 'ev-charging', label: 'EV Charging Station', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#0D9488' }, defaultProps: {} },
      { id: 'catch-basin', label: 'Stormwater Catch Basin', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#374151' }, defaultProps: {} },
      { id: 'storm-pipe', label: 'Stormwater Pipe', category: 'utilities', drawMode: 'line', defaultStyle: { strokeColor: '#3B82F6', lineType: 'dashed', strokeWidth: 1 }, defaultProps: {} },
      { id: 'storm-outfall', label: 'Stormwater Outfall', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#3B82F6' }, defaultProps: {} },
      { id: 'utility-pole', label: 'Utility Pole', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#78716C' }, defaultProps: {} },
      { id: 'power-line', label: 'Overhead Power Line', category: 'utilities', drawMode: 'line', defaultStyle: { strokeColor: '#64748B', strokeWidth: 1 }, defaultProps: {} },
      { id: 'transformer', label: 'Pad-Mounted Transformer', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#64748B' }, defaultProps: {} },
      { id: 'fire-hydrant', label: 'Fire Hydrant', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#DC2626' }, defaultProps: {} },
      { id: 'underground-util', label: 'Underground Utility Line', category: 'utilities', drawMode: 'line', defaultStyle: { strokeColor: '#FBBF24', lineType: 'dashed', strokeWidth: 1 }, defaultProps: { utilType: 'gas' } },
      { id: 'manhole', label: 'Manhole / Access Cover', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#374151' }, defaultProps: {} },
      { id: 'cell-tower', label: 'Cell Tower', category: 'utilities', drawMode: 'place', defaultStyle: { fillColor: '#64748B' }, defaultProps: {} },
    ]
  },
  {
    id: 'landscape', label: 'Landscape Surfaces', icon: 'water', color: '#22C55E',
    elements: [
      { id: 'lawn', label: 'Lawn / Turf', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#22C55E', fillOpacity: 85 }, defaultProps: {} },
      { id: 'meadow', label: 'Meadow / Native Planting', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#84CC16', fillOpacity: 85 }, defaultProps: {} },
      { id: 'forest', label: 'Forest / Tree Canopy', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#15803D', fillOpacity: 90 }, defaultProps: {} },
      { id: 'water', label: 'Water Body', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#3B82F6', fillOpacity: 80 }, defaultProps: {} },
      { id: 'wetland', label: 'Wetland / Marsh', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#4ADE80', fillOpacity: 70 }, defaultProps: {} },
      { id: 'beach', label: 'Beach / Sand', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF08A', fillOpacity: 80 }, defaultProps: {} },
      { id: 'rock', label: 'Rock / Outcrop', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#9CA3AF', fillOpacity: 80 }, defaultProps: {} },
      { id: 'mulch', label: 'Mulch / Planting Bed', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#92400E', fillOpacity: 90 }, defaultProps: {} },
      { id: 'decomposed-granite', label: 'Decomposed Granite', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#D97706', fillOpacity: 85 }, defaultProps: {} },
      { id: 'ice-snow', label: 'Ice / Snow', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#E0F2FE', fillOpacity: 80 }, defaultProps: {} },
      { id: 'agricultural', label: 'Agricultural Field', category: 'landscape', drawMode: 'polygon', defaultStyle: { fillColor: '#D9F99D', fillOpacity: 80 }, defaultProps: {} },
    ]
  },
  {
    id: 'planting', label: 'Planting', icon: 'tree', color: '#15803D',
    elements: [
      { id: 'tree', label: 'Tree (Individual)', category: 'planting', drawMode: 'circle', defaultStyle: { fillColor: '#22C55E' }, defaultProps: { canopyDiameter: 20, species: 'Oak' } },
      { id: 'street-tree', label: 'Street Tree (Row)', category: 'planting', drawMode: 'line', defaultStyle: { strokeColor: '#22C55E', strokeWidth: 2 }, defaultProps: { spacing: 30 } },
      { id: 'shrub', label: 'Shrub', category: 'planting', drawMode: 'circle', defaultStyle: { fillColor: '#16A34A' }, defaultProps: {} },
      { id: 'hedge', label: 'Hedge', category: 'planting', drawMode: 'line', defaultStyle: { strokeColor: '#15803D', strokeWidth: 2 }, defaultProps: { width: 3 } },
      { id: 'groundcover', label: 'Groundcover', category: 'planting', drawMode: 'polygon', defaultStyle: { fillColor: '#86EFAC', fillOpacity: 80 }, defaultProps: {} },
      { id: 'planting-bed', label: 'Planting Bed (Mixed Border)', category: 'planting', drawMode: 'polygon', defaultStyle: { fillColor: '#A3E635', fillOpacity: 80 }, defaultProps: {} },
      { id: 'vine', label: 'Vine / Climbing Plant', category: 'planting', drawMode: 'line', defaultStyle: { strokeColor: '#4ADE80', lineType: 'dashed', strokeWidth: 1 }, defaultProps: {} },
      { id: 'green-roof', label: 'Green Roof', category: 'planting', drawMode: 'polygon', defaultStyle: { fillColor: '#22C55E', fillOpacity: 60 }, defaultProps: {} },
      { id: 'espalier', label: 'Espalier / Wall Planting', category: 'planting', drawMode: 'line', defaultStyle: { strokeColor: '#4ADE80', strokeWidth: 1 }, defaultProps: {} },
    ]
  },
  {
    id: 'green-infra', label: 'Green Infrastructure', icon: 'water', color: '#0D9488',
    elements: [
      { id: 'bioswale', label: 'Bioswale', category: 'green-infra', drawMode: 'polygon', defaultStyle: { fillColor: '#4ADE80', fillOpacity: 70 }, defaultProps: {} },
      { id: 'rain-garden', label: 'Rain Garden', category: 'green-infra', drawMode: 'polygon', defaultStyle: { fillColor: '#22D3EE', fillOpacity: 70 }, defaultProps: {} },
      { id: 'retention-basin', label: 'Retention/Detention Basin', category: 'green-infra', drawMode: 'polygon', defaultStyle: { fillColor: '#3B82F6', fillOpacity: 60 }, defaultProps: {} },
      { id: 'permeable-paving', label: 'Permeable Paving Area', category: 'green-infra', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB', fillOpacity: 80 }, defaultProps: {} },
      { id: 'constructed-wetland', label: 'Constructed Wetland', category: 'green-infra', drawMode: 'polygon', defaultStyle: { fillColor: '#4ADE80', fillOpacity: 60 }, defaultProps: {} },
      { id: 'storm-tree-pit', label: 'Stormwater Tree Pit', category: 'green-infra', drawMode: 'place', defaultStyle: { fillColor: '#16A34A' }, defaultProps: {} },
    ]
  },
  {
    id: 'parks', label: 'Parks & Recreation', icon: 'tree', color: '#16A34A',
    elements: [
      { id: 'soccer-field', label: 'Soccer / Football Field', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#22C55E', fillOpacity: 80, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 360, heightFt: 220 } },
      { id: 'basketball-court', label: 'Basketball Court', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#C2863A', fillOpacity: 90, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 94, heightFt: 50 } },
      { id: 'tennis-court', label: 'Tennis Court', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#2563EB', fillOpacity: 80, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 120, heightFt: 60 } },
      { id: 'pickleball-court', label: 'Pickleball Court', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#7C3AED', fillOpacity: 80, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 64, heightFt: 34 } },
      { id: 'baseball-diamond', label: 'Baseball Diamond', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#16A34A', fillOpacity: 70, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 280, heightFt: 280 } },
      { id: 'running-track', label: 'Running Track', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#DC2626', fillOpacity: 70, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 370, heightFt: 230 } },
      { id: 'pool', label: 'Swimming Pool', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#0EA5E9', fillOpacity: 90, strokeColor: '#BFDBFE', strokeWidth: 1 }, defaultProps: { widthFt: 165, heightFt: 82 } },
      { id: 'splash-pad', label: 'Splash Pad / Water Play', category: 'parks', drawMode: 'polygon', defaultStyle: { fillColor: '#38BDF8', fillOpacity: 70 }, defaultProps: {} },
      { id: 'skate-park', label: 'Skate Park', category: 'parks', drawMode: 'polygon', defaultStyle: { fillColor: '#374151', fillOpacity: 90 }, defaultProps: {} },
      { id: 'dog-park', label: 'Dog Park', category: 'parks', drawMode: 'polygon', defaultStyle: { fillColor: '#A3E635', fillOpacity: 70, strokeColor: '#65A30D', strokeWidth: 2 }, defaultProps: {} },
      { id: 'playground-area', label: 'Playground Area', category: 'parks', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 70 }, defaultProps: {} },
      { id: 'bocce-court', label: 'Bocce / Pétanque Court', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#D97706', fillOpacity: 60, strokeColor: '#92400E', strokeWidth: 1 }, defaultProps: { widthFt: 90, heightFt: 14 } },
      { id: 'volleyball-court', label: 'Volleyball Court', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#FDE68A', fillOpacity: 70, strokeColor: '#FFFFFF', strokeWidth: 1 }, defaultProps: { widthFt: 80, heightFt: 50 } },
      { id: 'community-garden', label: 'Community Garden', category: 'parks', drawMode: 'polygon', defaultStyle: { fillColor: '#86EFAC', fillOpacity: 80, strokeColor: '#16A34A', strokeWidth: 1 }, defaultProps: {} },
      { id: 'amphitheater', label: 'Amphitheater / Bandshell', category: 'parks', drawMode: 'polygon', defaultStyle: { fillColor: '#CBD5E1', fillOpacity: 80 }, defaultProps: {} },
      { id: 'picnic-shelter', label: 'Picnic Shelter / Pavilion', category: 'parks', drawMode: 'place', defaultStyle: { fillColor: '#D97706', fillOpacity: 60, strokeColor: '#92400E', strokeWidth: 1 }, defaultProps: { widthFt: 40, heightFt: 30 } },
    ]
  },
  {
    id: 'actors', label: 'Actors', icon: 'person', color: '#F97316',
    elements: [
      { id: 'car', label: 'Automobile', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#3B82F6' }, defaultProps: {} },
      { id: 'bicyclist', label: 'Bicyclist', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#F97316' }, defaultProps: {} },
      { id: 'pedestrian', label: 'Pedestrian', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#F97316' }, defaultProps: {} },
      { id: 'scooter-rider', label: 'Scooter / E-Bike Rider', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#F97316' }, defaultProps: {} },
      { id: 'wheelchair-user', label: 'Wheelchair User', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#2563EB' }, defaultProps: {} },
      { id: 'delivery-vehicle', label: 'Delivery Vehicle', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#92400E' }, defaultProps: {} },
      { id: 'bus-vehicle', label: 'Bus (Illustrative)', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#FFFFFF' }, defaultProps: {} },
      { id: 'dog-walker', label: 'Dog (with walker)', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#92400E' }, defaultProps: {} },
      { id: 'outdoor-dining', label: 'Outdoor Dining Crowd', category: 'actors', drawMode: 'place', defaultStyle: { fillColor: '#F97316' }, defaultProps: { density: 'medium' } },
    ]
  },
  {
    id: 'annotations', label: 'Annotations', icon: 'dimension', color: '#F97316',
    elements: [
      { id: 'site-boundary', label: 'Site Boundary', category: 'annotations', drawMode: 'polygon', defaultStyle: { strokeColor: '#F97316', fillOpacity: 0, lineType: 'dashed', strokeWidth: 2 }, defaultProps: {} },
      { id: 'property-line', label: 'Property Line / Parcel Boundary', category: 'annotations', drawMode: 'polygon', defaultStyle: { strokeColor: '#DB2777', fillOpacity: 0, strokeWidth: 1 }, defaultProps: {} },
      { id: 'setback-line', label: 'Setback Line', category: 'annotations', drawMode: 'line', defaultStyle: { strokeColor: '#FBBF24', lineType: 'dashed', strokeWidth: 1 }, defaultProps: { type: 'front' } },
      { id: 'build-to-line', label: 'Build-To Line', category: 'annotations', drawMode: 'line', defaultStyle: { strokeColor: '#F97316', strokeWidth: 2 }, defaultProps: {} },
      { id: 'height-limit', label: 'Height Limit Overlay', category: 'annotations', drawMode: 'polygon', defaultStyle: { fillColor: '#BFDBFE', fillOpacity: 40 }, defaultProps: { heightLimit: 45 } },
      { id: 'view-corridor', label: 'View Corridor', category: 'annotations', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF08A', fillOpacity: 40 }, defaultProps: {} },
      { id: 'flood-zone', label: 'Flood Zone Boundary', category: 'annotations', drawMode: 'polygon', defaultStyle: { fillColor: '#3B82F6', fillOpacity: 25 }, defaultProps: { zone: 'AE' } },
      { id: 'easement', label: 'Easement', category: 'annotations', drawMode: 'polygon', defaultStyle: { fillColor: '#A78BFA', fillOpacity: 30 }, defaultProps: { type: 'utility' } },
      { id: 'phase-boundary', label: 'Phase Boundary', category: 'annotations', drawMode: 'polygon', defaultStyle: { strokeColor: '#F97316', lineType: 'dashed', fillOpacity: 0, strokeWidth: 2 }, defaultProps: {} },
      { id: 'survey-grid', label: 'Survey / Reference Grid', category: 'annotations', drawMode: 'polygon', defaultStyle: { strokeColor: '#94A3B8', lineType: 'dashed', fillOpacity: 0 }, defaultProps: { cellSize: 100 } },
    ]
  },
  {
    id: 'buildings', label: 'Buildings', icon: 'building', color: '#334155',
    elements: [
      { id: 'sfh', label: 'Single-Family Detached', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#334155', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 2, widthFt: 50, heightFt: 36 } },
      { id: 'duplex', label: 'Duplex', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#334155', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 2, widthFt: 64, heightFt: 36 } },
      { id: 'triplex', label: 'Triplex', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#334155', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 3, widthFt: 76, heightFt: 38 } },
      { id: 'fourplex', label: 'Fourplex', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#334155', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 2, widthFt: 60, heightFt: 44 } },
      { id: 'sixplex', label: 'Sixplex / Small Apartment', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#3D5168', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 3, widthFt: 90, heightFt: 55 } },
      { id: 'townhouse', label: 'Townhouse / Rowhouse', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#475569', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 3, widthFt: 22, heightFt: 44 } },
      { id: 'garden-apt', label: 'Garden Apartment', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#3D5168', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 3, widthFt: 140, heightFt: 65 } },
      { id: 'midrise', label: 'Mid-Rise Multifamily', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#334155', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 8, widthFt: 100, heightFt: 65 } },
      { id: 'highrise', label: 'High-Rise Residential Tower', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#1E293B', strokeColor: '#94A3B8', strokeWidth: 1 }, defaultProps: { floors: 20, widthFt: 90, heightFt: 90 } },
      { id: 'mixed-use', label: 'Mixed-Use Retail+Residential', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#1D4ED8', strokeColor: '#93C5FD', strokeWidth: 1 }, defaultProps: { floors: 5, widthFt: 120, heightFt: 65 } },
      { id: 'commercial', label: 'Commercial / Retail Strip', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#1D4ED8', strokeColor: '#93C5FD', strokeWidth: 1 }, defaultProps: { floors: 1, widthFt: 160, heightFt: 80 } },
      { id: 'office', label: 'Office Building', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#1E3A5F', strokeColor: '#93C5FD', strokeWidth: 1 }, defaultProps: { floors: 10, widthFt: 100, heightFt: 65 } },
      { id: 'hotel', label: 'Hotel', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#1E3A5F', strokeColor: '#93C5FD', strokeWidth: 1 }, defaultProps: { floors: 12, widthFt: 90, heightFt: 70 } },
      { id: 'industrial', label: 'Industrial / Warehouse', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#374151', strokeColor: '#9CA3AF', strokeWidth: 1 }, defaultProps: { floors: 1, widthFt: 220, heightFt: 130 } },
      { id: 'big-box', label: 'Big Box Retail', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#374151', strokeColor: '#9CA3AF', strokeWidth: 1 }, defaultProps: { floors: 1, widthFt: 250, heightFt: 200 } },
      { id: 'civic', label: 'Civic / Institutional', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#4C1D95', strokeColor: '#C4B5FD', strokeWidth: 1 }, defaultProps: { floors: 3, widthFt: 140, heightFt: 90 } },
      { id: 'school', label: 'School / Campus Building', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#4C1D95', strokeColor: '#C4B5FD', strokeWidth: 1 }, defaultProps: { floors: 2, widthFt: 220, heightFt: 110 } },
      { id: 'religious', label: 'Religious / Place of Worship', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#4C1D95', strokeColor: '#C4B5FD', strokeWidth: 1 }, defaultProps: { floors: 1, widthFt: 80, heightFt: 60 } },
      { id: 'hospital', label: 'Hospital / Medical Campus', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#1E3A5F', strokeColor: '#93C5FD', strokeWidth: 1 }, defaultProps: { floors: 6, widthFt: 250, heightFt: 160 } },
      { id: 'data-center', label: 'Data Center', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#374151', strokeColor: '#9CA3AF', strokeWidth: 1 }, defaultProps: { floors: 2, widthFt: 220, heightFt: 160 } },
      { id: 'parking-deck', label: 'Parking Structure', category: 'buildings', drawMode: 'place', defaultStyle: { fillColor: '#374151', strokeColor: '#9CA3AF', strokeWidth: 1 }, defaultProps: { levels: 6, widthFt: 260, heightFt: 85 } },
    ]
  },
  {
    id: 'landuse', label: 'Land Use, Zoning & FBC Overlays', icon: 'grid', color: '#F59E0B',
    elements: [
      // General Land Use
      { id: 'lu-low-res', label: 'Low-Density Residential', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FDE68A', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-med-res', label: 'Medium-Density Residential', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-high-res', label: 'High-Density Residential', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCA5A5', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-mixed', label: 'Mixed Use', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F9A8D4', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-commercial', label: 'Commercial / Retail', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FECACA', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-office', label: 'Office', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#BFDBFE', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-industrial', label: 'Industrial / Warehouse', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#E5E7EB', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-civic', label: 'Civic / Institutional', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#C4B5FD', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-parks', label: 'Parks & Open Space', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#6EE7B7', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-agricultural', label: 'Agricultural', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#D9F99D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-infrastructure', label: 'Infrastructure / Utility', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#BAE6FD', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-vacant', label: 'Vacant / Underutilized', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F1F5F9', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-tod', label: 'Transit-Oriented Development', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#E0E7FF', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-waterfront', label: 'Waterfront / Harbor', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#CFFAFE', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lu-special', label: 'Special District / BID', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FED7AA', fillOpacity: 50 }, defaultProps: {} },
      // Conventional Zoning
      { id: 'z-r1', label: 'Single-Family Residential (R-1)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF9C3', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-r2', label: 'Two-Family / Duplex (R-2)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF08A', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-r3', label: 'Low-Density Multifamily (R-3)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FDE68A', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-r4', label: 'Medium-Density Multifamily (R-4)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-r5', label: 'High-Density Multifamily (R-5)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F59E0B', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-c1', label: 'Neighborhood Commercial (C-1)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCA5A5', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-c2', label: 'General Commercial (C-2)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F87171', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-c3', label: 'Downtown / Urban Commercial (C-3)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#EF4444', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-mx1', label: 'Mixed-Use Residential (MX-1)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F9A8D4', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-mx2', label: 'Mixed-Use Commercial (MX-2)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F472B6', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-o1', label: 'Office / Business Park (O-1)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#BFDBFE', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-i1', label: 'Light Industrial (I-1)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#D1D5DB', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-i2', label: 'Heavy Industrial (I-2)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#9CA3AF', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-p', label: 'Public / Civic (P)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#C4B5FD', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-os', label: 'Open Space / Recreation (OS)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#6EE7B7', fillOpacity: 50 }, defaultProps: {} },
      { id: 'z-pd', label: 'Planned Development (PD)', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#A7F3D0', fillOpacity: 50 }, defaultProps: {} },
      // FBC Transect
      { id: 'fbc-t1', label: 'T1 — Natural Zone', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#D1FAE5', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-t2', label: 'T2 — Rural Zone', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#A7F3D0', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-t3', label: 'T3 — Sub-Urban Zone', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF9C3', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-t4', label: 'T4 — General Urban Zone', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF08A', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-t5', label: 'T5 — Urban Center Zone', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-t6', label: 'T6 — Urban Core Zone', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F59E0B', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-sd', label: 'SD — Special District', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FED7AA', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-cs', label: 'CS — Civic Space', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#6EE7B7', fillOpacity: 50 }, defaultProps: {} },
      { id: 'fbc-cb', label: 'CB — Civic Building', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#C4B5FD', fillOpacity: 50 }, defaultProps: {} },
      // FBC Lot Types
      { id: 'lot-cottage', label: 'Cottage / Bungalow Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF9C3', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-sfh', label: 'Single-Family House Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FEF3C7', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-adu', label: 'Carriage House / ADU Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FDE68A', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-townhouse', label: 'Townhouse Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-duplex-side', label: 'Side-by-Side Duplex Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCD34D', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-duplex-stack', label: 'Stacked Duplex / Triplex Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FBBF24', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-courtyard', label: 'Courtyard Building Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F59E0B', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-livework', label: 'Live-Work Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#FCA5A5', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-shopfront', label: 'Shopfront / Main Street Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#F87171', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-mixeduse-block', label: 'Mixed-Use Block / Liner Building', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#EF4444', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-civic', label: 'Civic Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#C4B5FD', fillOpacity: 50 }, defaultProps: {} },
      { id: 'lot-open-space', label: 'Open Space / Civic Space Lot', category: 'landuse', drawMode: 'polygon', defaultStyle: { fillColor: '#6EE7B7', fillOpacity: 50 }, defaultProps: {} },
      // FBC Regulating Plan
      { id: 'fbc-zone-boundary', label: 'Regulating Plan Zone Boundary', category: 'landuse', drawMode: 'polygon', defaultStyle: { strokeColor: '#F59E0B', strokeWidth: 2, fillOpacity: 40 }, defaultProps: {} },
      { id: 'fbc-frontage-type', label: 'Frontage Type Line', category: 'landuse', drawMode: 'line', defaultStyle: { strokeColor: '#F97316', strokeWidth: 4 }, defaultProps: {} },
      { id: 'fbc-requirement-flag', label: 'Special Requirement Flag', category: 'landuse', drawMode: 'place', defaultStyle: { fillColor: '#F97316' }, defaultProps: {} },
      { id: 'fbc-street-type', label: 'Street Type Assignment', category: 'landuse', drawMode: 'line', defaultStyle: { strokeColor: '#2563EB', strokeWidth: 3 }, defaultProps: {} },
    ]
  },
]
